version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
            - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
            - ./prometheus/alert:/prometheus/alert
    command: "--config.file=/prometheus/prometheus.yml"
    #--storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
     - 80:3000
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/etc/:/etc/grafana/provisioning/
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
    ports:
      - '9093:9093'

  ##############################
  # logs metrics managment
  ##############################
  
  loki:
    container_name: log-monitoring-loki
    image: grafana/loki:1.5.0
    #ports:
    #  - "3100:3100"
    restart: always

  promtail:
    container_name: log-monitoring-promtail
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
      - ./logs/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    restart: always

networks:
  loki:
