global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/prometheus/alert/alert1.rule"
    #- "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'node_exporter'
  static_configs:
  - targets: ['10.0.0.25:9100']
    labels:
        group: 'web'
  - targets: ['10.0.0.5:9100']
    labels:
        group: 'db'
- job_name: 'traefik'
  static_configs:
  - targets: ['10.0.0.25:8080']
- job_name: 'postgres'
  static_configs:
  - targets: ['10.0.0.5:9187']
- job_name: 'loki'
  static_configs:
  - targets: ['loki:3100']
- job_name: 'docker'
  static_configs:
  - targets: ['10.0.0.25:9323']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
